# Generated by Django 5.0.3 on 2024-10-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
