# Generated by Django 5.0.3 on 2024-10-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_sell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
