# Generated by Django 5.0.3 on 2024-10-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
